---
- name: Include distro-specific vars.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution }}.yml"

- name: Set base packages var.
  set_fact:
    build_debian_package_base_dependencies: "{{ __build_debian_package_base_dependencies }}"
  when: build_debian_package_base_dependencies is not defined
