---
# tasks file for build-debian-package
- include: include_distro_vars.yml
  tags: vars

- include: validate_variables.yml
  tags: validate

- include: packages.yml
  tags: packages

- include: create_directories.yml
  tags: directories

- include: pip_wheel.yml
  when: build_debian_package_pip_requirements is defined and
        build_debian_package_pip_requirements != ""
  tags:
    - pip
    - wheel

- include: build_debian_package.yml
  tags: build
