---
# The Debian control file fields should be validated prior to building.
# This role assumes that binary Debian packages are being built,
# which have slightly different (and more lax) requirements for fields.
# See docs at https://www.debian.org/doc/debian-policy/ch-controlfields.html
# More info can be fonud in vars/main.yml in this role.

- name: Validate required fields for DEBIAN/control file.
  fail:
    msg: |
      The Debian control field "{{ item }}" is not declared,
      but is required for building Debian packages. The list of required fields is:
      {% for field in build_debian_package_required_control_fields %}
        {{ field }}
      {% endfor %}
      See https://www.debian.org/doc/debian-policy/ch-controlfields.html
      for more information.
  with_items: "{{ build_debian_package_required_control_fields }}"
  when: item not in build_debian_package_control_fields

- name: Validate recommended fields for DEBIAN/control file.
  debug:
    msg: |
      The Debian control field "{{ item }}" is not declared,
      but is recommended for building Debian packages. The list of recommended fields is:
      {% for field in build_debian_package_recommended_control_fields %}
        {{ field }}
      {% endfor %}
      See https://www.debian.org/doc/debian-policy/ch-controlfields.html
      for more information.
  with_items: "{{ build_debian_package_recommended_control_fields }}"
  when: item not in build_debian_package_control_fields
